---
title: "Hackathon Kickoff!"
format:
  revealjs:
    width: 1060
    height: 900
    minScale: 0.2
    maxScale: 2.0
    self-contained: true
    theme: night
---

## Welcome to the pre-stats awayday hackathon!

-   Welcome everyone! We're thrilled to have you here.!

-   Get ready for 2 days of upskilling, creativity, collaboration, and innovation.

-   Over the next two days, you will be working on a project that you will present here and in the stats awayday on the 11th of September.

## Agenda

### 📅 Day 1 – 3rd September 2025

1.  🟢**Welcome & Kickoff**

2.  🧠**Project Planning**

3.  ☕ **Morning Break**

4.  💻 **Hacking Session #1**

5.  🍽️ **Lunch Break**

6.  💬 **Team Check-In**

7.  💻 **Hacking Session #2**

8.  ☕ **Afternoon Break**

9.  💬 **Team Check-In & Wrap-Up**

## Hackathon Guide - Event details

-   A section that summarises the event details and links to our code of conduct.

-   Please make sure to read it and follow it as we want to create a friendly and welcoming environment for everyone.

::: callout-tip
#### **Expected Behaviour**

To help create a positive and collaborative environment, we ask all participants to:

-   Be kind, respectful, and inclusive

-   Listen actively and value different perspectives

-   Give constructive feedback and accept it graciously

-   Collaborate with curiosity and openness

-   Help foster a fun and supportive atmosphere
:::

## Hackatghon Guide

INSERT SCREENSHOT

-   This guide was emailed to you before today

-   You can also find it in the Hackathon MS Team resources.

## Hackathon Guide - Agenda:

The plans for both days and can be accessed through the tabsets

INSERT SCREENSHOT HERE OR DEMO

## Hackathon Guide - Project information:

Read through all the project information. We worked with the teams who proposed the projects to give you as many resources as we can to support you with your projects.

-   The problem the project aims to solve

-   Skills you will develop by working on this project

-   Known challenges and limitations

-   Vision for the project by the end of the hackathon

## Hackathon Guide - Data and tools

Links to where you can find the data you need and how to access it and suggestions for tools you can use.

## Hackathon Guide - Support available:

-   Links to DataCamp courses

-   Links to other resources

-   MS Teams and volunteers

    -   Link to the Team for the hackathon where you can post question.

    -   We encourage you to use the 'Help and Support' channel to ask questions.

    -   Volunteers will try to answer when they're available and we also encourage you to support each other.

## Hackathon Guide - Your presentation

-   You will get to present at the end of the two day hackathon and also present at the stats awayday!

-   We provided a guided structure to help you create your presentation.

## Volunteers and organisers

## Let's get started!

1.  Set up a teams chat with your team

2.  Set up a call with your team to plan your project

3.  Things to consider:

    -   Project planning tools

    -   The coding language you will use

    -   Break down the project and assign parts to different members

    -   How you can utilize different people's expertise while still pushing for development

    -   Make sure to set up calls for the team check-ins scheduled in the agenda
